### PR TITLE
Add web-performance-research repo

### PR DESCRIPTION
**Pull request by imteekay**
## Change

- Other Awesome Lists

## Description of changes

- Add [`web-performance-research`](https://github.com/imteekay/web-performance-research) repo

### CODE REVIEW

**Comment by imteekay** [comment]
cc @davidsonfellipe

**Comment by imteekay** [comment]
cc @davidsonfellipe

**Review by nucliweb — APPROVED** [review]
👏

**Comment by NannaG4nine** [comment]
I'm sorry, but do not understand Codes, Java script etc... is this platform more for computer geeks, I'm trying to figure out how to store all my photos into a secure folder, I don't believe you sell from here, do you? If so imageappreciate it. I do have a FB page set up, but I've not launched anything yet. I'm probably in the wrong type platform? image

**Review by NannaG4nine — COMMENTED** [review]
I don't know what I am
doing here! I do know that, and I don't understand code that only computer geeks would know. This isn't a buy sale platform, but rather more for those growing great concept idea groups, and businesses, am I thinking right? I do know small business, took some courses , because I had a professional cleaning business; never sell 50 or 51% to investors. They can buy it out from under you.

**Pull request closed without merging**
