### PR TITLE
remove Libra

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by davidsonfellipe** [comment]
@DanielRuf hey daniel, just clarifying... What's the reason to delete that?

**Comment by DanielRuf** [comment]
It looks like it isn't actively maintained anymore and the last changes in the repositories from the org account are 4 years old. So getting any support may not be possible.

**Comment by DanielRuf** [comment]
Also their website is offline.

**Comment by davidsonfellipe** [comment]
@DanielRuf thanks

**Pull request merged**
